//
//  accent.c
//
//  Created by Jeremy on 4/15/15.
//  Copyright (c) 2015 Jeremy March. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//


//#include <stdlib.h> // For random(), RAND_MAX
//#include <string.h>  //for strlen()
#include "GreekUnicode.h"
#include "accent.h"

#define ALLOW_PRIVATE_USE_AREA 1
#define ALLOW_RHO_WITH_PSILI 1
#define MAX_COMBINING 5 //macron, breathing, accent, iota subscript || diaeresis, macron, accent

char unicode_mode = PRECOMPOSED_MODE; //set default
bool addSpacingDiacriticIfNotLegal = true;

void allowSpacingDiacritics(bool val)
{
    addSpacingDiacriticIfNotLegal = val;
}

#define NUM_COMBINING_ACCENTS 9
//this is the order they will follow after the vowel
unsigned short combiningAccents[NUM_COMBINING_ACCENTS] = { COMBINING_MACRON, COMBINING_BREVE, COMBINING_DIAERESIS, COMBINING_ROUGH_BREATHING, COMBINING_SMOOTH_BREATHING, COMBINING_ACUTE, COMBINING_GRAVE, COMBINING_CIRCUMFLEX, COMBINING_IOTA_SUBSCRIPT };

//precomposed indices
enum {
    NORMAL,
    TONOS,
    DIALYTIKA_AND_TONOS,
    PSILI,                                  //smooth
    DASIA,                                  //rough
    OXIA,
    PSILI_AND_OXIA,
    DASIA_AND_OXIA,
    VARIA,
    PSILI_AND_VARIA,
    DASIA_AND_VARIA,
    PERISPOMENI,
    PSILI_AND_PERISPOMENI,
    DASIA_AND_PERISPOMENI,
    YPOGEGRAMMENI,
    PSILI_AND_YPOGEGRAMMENI,
    DASIA_AND_YPOGEGRAMMENI,
    OXIA_AND_YPOGEGRAMMENI,
    PSILI_AND_OXIA_AND_YPOGEGRAMMENI,
    DASIA_AND_OXIA_AND_YPOGEGRAMMENI,
    VARIA_AND_YPOGEGRAMMENI,
    PSILI_AND_VARIA_AND_YPOGEGRAMMENI,
    DASIA_AND_VARIA_AND_YPOGEGRAMMENI,
    PERISPOMENI_AND_YPOGEGRAMMENI,
    PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI,
    DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI,
    DIALYTIKA,
    DIALYTIKA_AND_OXIA,
    DIALYTIKA_AND_VARIA,
    DIALYTIKA_AND_PERISPOMENON,
    MACRON_PRECOMPOSED,
#ifdef ALLOW_PRIVATE_USE_AREA
    MACRON_AND_SMOOTH,
    MACRON_AND_SMOOTH_AND_ACUTE,
    MACRON_AND_SMOOTH_AND_GRAVE,
    MACRON_AND_ROUGH,
    MACRON_AND_ROUGH_AND_ACUTE,
    MACRON_AND_ROUGH_AND_GRAVE,
    MACRON_AND_ACUTE,
    MACRON_AND_GRAVE,
#endif
    NUM_ACCENT_CODES
};

//letterCodes
enum {
    ALPHA,
    EPSILON,
    ETA,
    IOTA,
    OMICRON,
    UPSILON,
    OMEGA,
    ALPHA_CAP,
    EPSILON_CAP,
    ETA_CAP,
    IOTA_CAP,
    OMICRON_CAP,
    UPSILON_CAP,
    OMEGA_CAP,
    NUM_VOWEL_CODES
};

unsigned short letters[NUM_VOWEL_CODES][NUM_ACCENT_CODES] = {
    { GREEK_SMALL_LETTER_ALPHA, GREEK_SMALL_LETTER_ALPHA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA, GREEK_SMALL_LETTER_ALPHA_WITH_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_ALPHA_WITH_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_ALPHA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_ALPHA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0,
        GREEK_SMALL_LETTER_ALPHA_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_MACRON2,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_ALPHA_WITH_VARIA_AND_MACRON
#endif
    },
    
    { GREEK_SMALL_LETTER_EPSILON,GREEK_SMALL_LETTER_EPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA, GREEK_SMALL_LETTER_EPSILON_WITH_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_EPSILON_WITH_VARIA, GREEK_SMALL_LETTER_EPSILON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_EPSILON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_ETA, GREEK_SMALL_LETTER_ETA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_ETA_WITH_PSILI, GREEK_SMALL_LETTER_ETA_WITH_DASIA, GREEK_SMALL_LETTER_ETA_WITH_OXIA, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_ETA_WITH_VARIA, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_ETA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_ETA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_IOTA, GREEK_SMALL_LETTER_IOTA_WITH_TONOS, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_TONOS, GREEK_SMALL_LETTER_IOTA_WITH_PSILI, GREEK_SMALL_LETTER_IOTA_WITH_DASIA, GREEK_SMALL_LETTER_IOTA_WITH_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_OXIA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_VARIA, GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_PERISPOMENI,
        GREEK_SMALL_LETTER_IOTA_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_IOTA_WITH_VARIA_AND_MACRON
#endif
    },
    
    { GREEK_SMALL_LETTER_OMICRON, GREEK_SMALL_LETTER_OMICRON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA, GREEK_SMALL_LETTER_OMICRON_WITH_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_OMICRON_WITH_VARIA, GREEK_SMALL_LETTER_OMICRON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_OMICRON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_SMALL_LETTER_UPSILON, GREEK_SMALL_LETTER_UPSILON_WITH_TONOS, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_TONOS, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA, GREEK_SMALL_LETTER_UPSILON_WITH_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_PERISPOMENI, GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_OXIA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_VARIA, GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_PERISPOMENI,
        GREEK_SMALL_LETTER_UPSILON_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_PSILI_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_DASIA_AND_VARIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_OXIA_AND_MACRON,
        PUA_GREEK_SMALL_LETTER_UPSILON_WITH_VARIA_AND_MACRON
#endif
    },
    
    { GREEK_SMALL_LETTER_OMEGA, GREEK_SMALL_LETTER_OMEGA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA, GREEK_SMALL_LETTER_OMEGA_WITH_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_OXIA, GREEK_SMALL_LETTER_OMEGA_WITH_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_VARIA, GREEK_SMALL_LETTER_OMEGA_WITH_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI, GREEK_SMALL_LETTER_OMEGA_WITH_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_OXIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_VARIA_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI, GREEK_SMALL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    /* START CAPITALS */
    { GREEK_CAPITAL_LETTER_ALPHA,GREEK_CAPITAL_LETTER_ALPHA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_VARIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ALPHA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ALPHA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ALPHA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_ALPHA_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_EPSILON, GREEK_CAPITAL_LETTER_EPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_VARIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_EPSILON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_ETA, GREEK_CAPITAL_LETTER_ETA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA, GREEK_CAPITAL_LETTER_ETA_WITH_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_ETA_WITH_VARIA, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_ETA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_ETA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_ETA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_ETA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_IOTA, GREEK_CAPITAL_LETTER_IOTA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA, GREEK_CAPITAL_LETTER_IOTA_WITH_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_IOTA_WITH_VARIA, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_IOTA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_IOTA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_IOTA_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_IOTA_WITH_DIALYTIKA, 0, 0, 0, GREEK_CAPITAL_LETTER_IOTA_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    { GREEK_CAPITAL_LETTER_OMICRON, GREEK_CAPITAL_LETTER_OMICRON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_VARIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_OMICRON_WITH_DASIA_AND_VARIA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_UPSILON, GREEK_CAPITAL_LETTER_UPSILON_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA, GREEK_CAPITAL_LETTER_UPSILON_WITH_OXIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_OXIA*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_UPSILON_WITH_VARIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_VARIA*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PERISPOMENI*/, 0/*GREEK_CAPITAL_LETTER_UPSILON_WITH_PSILI_AND_PERISPOMENI*/, GREEK_CAPITAL_LETTER_UPSILON_WITH_DASIA_AND_PERISPOMENI, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, GREEK_CAPITAL_LETTER_UPSILON_WITH_DIALYTIKA, 0, 0, 0, GREEK_CAPITAL_LETTER_UPSILON_WITH_MACRON
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    },
    
    { GREEK_CAPITAL_LETTER_OMEGA, GREEK_CAPITAL_LETTER_OMEGA_WITH_TONOS, 0 /* DIALYTIKA_AND_TONOS */, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_OXIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_VARIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_VARIA, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_VARIA, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_PERISPOMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_OXIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_OXIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_OXIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_VARIA_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_VARIA_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_VARIA_AND_PROSGEGRAMMENI, 0/*GREEK_CAPITAL_LETTER_OMEGA_WITH_PERISPOMENI_AND_PROSGEGRAMMENI*/, GREEK_CAPITAL_LETTER_OMEGA_WITH_PSILI_AND_PERISPOMENI_AND_PROSGEGRAMMENI, GREEK_CAPITAL_LETTER_OMEGA_WITH_DASIA_AND_PERISPOMENI_AND_PROSGEGRAMMENI, 0, 0, 0, 0, 0
#ifdef ALLOW_PRIVATE_USE_AREA
        , 0, 0, 0, 0, 0, 0, 0, 0
#endif
    }
};

#define NOCHAR -1
short basicGreekLookUp[][2] = {
    /* 0370 */ { NOCHAR, NOCHAR },
    /* 0371 */ { NOCHAR, NOCHAR },
    /* 0372 */ { NOCHAR, NOCHAR },
    /* 0373 */ { NOCHAR, NOCHAR },
    /* 0374 */ { NOCHAR, NOCHAR },
    /* 0375 */ { NOCHAR, NOCHAR },
    /* 0376 */ { NOCHAR, NOCHAR },
    /* 0377 */ { NOCHAR, NOCHAR },
    /* 0378 */ { NOCHAR, NOCHAR },
    /* 0379 */ { NOCHAR, NOCHAR },
    /* 037A */ { NOCHAR, NOCHAR },
    /* 037B */ { NOCHAR, NOCHAR },
    /* 037C */ { NOCHAR, NOCHAR },
    /* 037D */ { NOCHAR, NOCHAR },
    /* 037E */ { NOCHAR, NOCHAR },
    /* 037F */ { NOCHAR, NOCHAR },
    /* 0380 */ { NOCHAR, NOCHAR },
    /* 0381 */ { NOCHAR, NOCHAR },
    /* 0382 */ { NOCHAR, NOCHAR },
    /* 0383 */ { NOCHAR, NOCHAR },
    /* 0384 */ { NOCHAR, NOCHAR },
    /* 0385 */ { NOCHAR, NOCHAR },
    /* 0386 */ { ALPHA_CAP, TONOS },
    /* 0387 */ { NOCHAR, NOCHAR },
    /* 0388 */ { EPSILON_CAP, TONOS },
    /* 0389 */ { ETA_CAP, TONOS },
    /* 038A */ { IOTA_CAP, TONOS },
    /* 038B */ { NOCHAR, NOCHAR },
    /* 038C */ { OMICRON_CAP, TONOS },
    /* 038D */ { NOCHAR, NOCHAR },
    /* 038E */ { UPSILON_CAP, TONOS },
    /* 038F */ { OMEGA_CAP, TONOS },
    /* 0390 */ { IOTA, DIALYTIKA_AND_TONOS },
    /* 0391 */ { ALPHA_CAP, NORMAL },
    /* 0392 */ { NOCHAR, NOCHAR },
    /* 0393 */ { NOCHAR, NOCHAR },
    /* 0394 */ { NOCHAR, NOCHAR },
    /* 0395 */ { EPSILON_CAP, NORMAL },
    /* 0396 */ { NOCHAR, NOCHAR },
    /* 0397 */ { ETA_CAP, NORMAL },
    /* 0398 */ { NOCHAR, NOCHAR },
    /* 0399 */ { IOTA_CAP, NORMAL },
    /* 039A */ { NOCHAR, NOCHAR },
    /* 039B */ { NOCHAR, NOCHAR },
    /* 039C */ { NOCHAR, NOCHAR },
    /* 039D */ { NOCHAR, NOCHAR },
    /* 039E */ { NOCHAR, NOCHAR },
    /* 039F */ { OMICRON_CAP, NORMAL },
    /* 03A0 */ { NOCHAR, NOCHAR },
    /* 03A1 */ { NOCHAR, NOCHAR },
    /* 03A2 */ { NOCHAR, NOCHAR },
    /* 03A3 */ { NOCHAR, NOCHAR },
    /* 03A4 */ { NOCHAR, NOCHAR },
    /* 03A5 */ { UPSILON_CAP, NORMAL },
    /* 03A6 */ { NOCHAR, NOCHAR },
    /* 03A7 */ { NOCHAR, NOCHAR },
    /* 03A8 */ { NOCHAR, NOCHAR },
    /* 03A9 */ { OMEGA_CAP, NORMAL },
    /* 03AA */ { IOTA_CAP, DIALYTIKA },
    /* 03AB */ { UPSILON_CAP, DIALYTIKA },
    /* 03AC */ { ALPHA, TONOS },
    /* 03AD */ { EPSILON, TONOS },
    /* 03AE */ { ETA, TONOS },
    /* 03AF */ { IOTA, TONOS },
    /* 03B0 */ { UPSILON, DIALYTIKA_AND_TONOS },
    /* 03B1 */ { ALPHA, NORMAL },
    /* 03B2 */ { NOCHAR, NOCHAR },
    /* 03B3 */ { NOCHAR, NOCHAR },
    /* 03B4 */ { NOCHAR, NOCHAR },
    /* 03B5 */ { EPSILON, NORMAL },
    /* 03B6 */ { NOCHAR, NOCHAR },
    /* 03B7 */ { ETA, NORMAL },
    /* 03B8 */ { NOCHAR, NOCHAR },
    /* 03B9 */ { IOTA, NORMAL },
    /* 03BA */ { NOCHAR, NOCHAR },
    /* 03BB */ { NOCHAR, NOCHAR },
    /* 03BC */ { NOCHAR, NOCHAR },
    /* 03BD */ { NOCHAR, NOCHAR },
    /* 03BE */ { NOCHAR, NOCHAR },
    /* 03BF */ { OMICRON, NORMAL },
    /* 03C0 */ { NOCHAR, NOCHAR },
    /* 03C1 */ { NOCHAR, NOCHAR },
    /* 03C2 */ { NOCHAR, NOCHAR },
    /* 03C3 */ { NOCHAR, NOCHAR },
    /* 03C4 */ { NOCHAR, NOCHAR },
    /* 03C5 */ { UPSILON, NORMAL },
    /* 03C6 */ { NOCHAR, NOCHAR },
    /* 03C7 */ { NOCHAR, NOCHAR },
    /* 03C8 */ { NOCHAR, NOCHAR },
    /* 03C9 */ { OMEGA, NORMAL },
    /* 03CA */ { IOTA, DIALYTIKA },
    /* 03CB */ { UPSILON, DIALYTIKA },
    /* 03CC */ { OMICRON, TONOS },
    /* 03CD */ { UPSILON, TONOS },
    /* 03CE */ { OMEGA, TONOS },
    /* 03CF */ { NOCHAR, NOCHAR },
    /* 03D0 */ { NOCHAR, NOCHAR },
    /* 03D1 */ { NOCHAR, NOCHAR },
    /* 03D2 */ { NOCHAR, NOCHAR },
    /* 03D3 */ { NOCHAR, NOCHAR },
    /* 03D4 */ { NOCHAR, NOCHAR },
    /* 03D5 */ { NOCHAR, NOCHAR },
    /* 03D6 */ { NOCHAR, NOCHAR },
    /* 03D7 */ { NOCHAR, NOCHAR },
    /* 03D8 */ { NOCHAR, NOCHAR },
    /* 03D9 */ { NOCHAR, NOCHAR },
    /* 03DA */ { NOCHAR, NOCHAR },
    /* 03DB */ { NOCHAR, NOCHAR },
    /* 03DC */ { NOCHAR, NOCHAR },
    /* 03DD */ { NOCHAR, NOCHAR },
    /* 03DE */ { NOCHAR, NOCHAR },
    /* 03DF */ { NOCHAR, NOCHAR },
    /* 03E0 */ { NOCHAR, NOCHAR },
    /* 03E1 */ { NOCHAR, NOCHAR },
    /* 03E2 */ { NOCHAR, NOCHAR },
    /* 03E3 */ { NOCHAR, NOCHAR },
    /* 03E4 */ { NOCHAR, NOCHAR },
    /* 03E5 */ { NOCHAR, NOCHAR },
    /* 03E6 */ { NOCHAR, NOCHAR },
    /* 03E7 */ { NOCHAR, NOCHAR },
    /* 03E8 */ { NOCHAR, NOCHAR },
    /* 03E9 */ { NOCHAR, NOCHAR },
    /* 03EA */ { NOCHAR, NOCHAR },
    /* 03EB */ { NOCHAR, NOCHAR },
    /* 03EC */ { NOCHAR, NOCHAR },
    /* 03ED */ { NOCHAR, NOCHAR },
    /* 03EE */ { NOCHAR, NOCHAR },
    /* 03EF */ { NOCHAR, NOCHAR },
    /* 03F0 */ { NOCHAR, NOCHAR },
    /* 03F1 */ { NOCHAR, NOCHAR },
    /* 03F2 */ { NOCHAR, NOCHAR },
    /* 03F3 */ { NOCHAR, NOCHAR },
    /* 03F4 */ { NOCHAR, NOCHAR },
    /* 03F5 */ { NOCHAR, NOCHAR },
    /* 03F6 */ { NOCHAR, NOCHAR },
    /* 03F7 */ { NOCHAR, NOCHAR },
    /* 03F8 */ { NOCHAR, NOCHAR },
    /* 03F9 */ { NOCHAR, NOCHAR },
    /* 03FA */ { NOCHAR, NOCHAR },
    /* 03FB */ { NOCHAR, NOCHAR },
    /* 03FC */ { NOCHAR, NOCHAR },
    /* 03FD */ { NOCHAR, NOCHAR },
    /* 03FE */ { NOCHAR, NOCHAR },
    /* 03FF */ { NOCHAR, NOCHAR }
};
    
short extendedGreekLookUp[][2] = {
    /* 1F00 */ { ALPHA, PSILI },
    /* 1F01 */ { ALPHA, DASIA },
    /* 1F02 */ { ALPHA, PSILI_AND_VARIA },
    /* 1F03 */ { ALPHA, DASIA_AND_VARIA },
    /* 1F04 */ { ALPHA, PSILI_AND_OXIA },
    /* 1F05 */ { ALPHA, DASIA_AND_OXIA },
    /* 1F06 */ { ALPHA, PSILI_AND_PERISPOMENI },
    /* 1F07 */ { ALPHA, DASIA_AND_PERISPOMENI },
    /* 1F08 */ { ALPHA_CAP, PSILI },
    /* 1F09 */ { ALPHA_CAP, DASIA },
    /* 1F0A */ { ALPHA_CAP, PSILI_AND_VARIA },
    /* 1F0B */ { ALPHA_CAP, DASIA_AND_VARIA },
    /* 1F0C */ { ALPHA_CAP, PSILI_AND_OXIA },
    /* 1F0D */ { ALPHA_CAP, DASIA_AND_OXIA },
    /* 1F0E */ { ALPHA_CAP, PSILI_AND_PERISPOMENI },
    /* 1F0F */ { ALPHA_CAP, DASIA_AND_PERISPOMENI },
    /* 1F10 */ { EPSILON, PSILI },
    /* 1F11 */ { EPSILON, DASIA },
    /* 1F12 */ { EPSILON, PSILI_AND_VARIA },
    /* 1F13 */ { EPSILON, DASIA_AND_VARIA },
    /* 1F14 */ { EPSILON, PSILI_AND_OXIA },
    /* 1F15 */ { EPSILON, DASIA_AND_OXIA },
    /* 1F16 */ { NOCHAR, NOCHAR },
    /* 1F17 */ { NOCHAR, NOCHAR },
    /* 1F18 */ { EPSILON_CAP, PSILI },
    /* 1F19 */ { EPSILON_CAP, DASIA },
    /* 1F1A */ { EPSILON_CAP, PSILI_AND_VARIA },
    /* 1F1B */ { EPSILON_CAP, DASIA_AND_VARIA },
    /* 1F1C */ { EPSILON_CAP, PSILI_AND_OXIA },
    /* 1F1D */ { EPSILON_CAP, DASIA_AND_OXIA },
    /* 1F1E */ { NOCHAR, NOCHAR },
    /* 1F1F */ { NOCHAR, NOCHAR },
    /* 1F20 */ { ETA, PSILI },
    /* 1F21 */ { ETA, DASIA },
    /* 1F22 */ { ETA, PSILI_AND_VARIA },
    /* 1F23 */ { ETA, DASIA_AND_VARIA },
    /* 1F24 */ { ETA, PSILI_AND_OXIA },
    /* 1F25 */ { ETA, DASIA_AND_OXIA },
    /* 1F26 */ { ETA, PSILI_AND_PERISPOMENI },
    /* 1F27 */ { ETA, DASIA_AND_PERISPOMENI },
    /* 1F28 */ { ETA_CAP, PSILI },
    /* 1F29 */ { ETA_CAP, DASIA },
    /* 1F2A */ { ETA_CAP, PSILI_AND_VARIA },
    /* 1F2B */ { ETA_CAP, DASIA_AND_VARIA },
    /* 1F2C */ { ETA_CAP, PSILI_AND_OXIA },
    /* 1F2D */ { ETA_CAP, DASIA_AND_OXIA },
    /* 1F2E */ { ETA_CAP, PSILI_AND_PERISPOMENI },
    /* 1F2F */ { ETA_CAP, DASIA_AND_PERISPOMENI },
    /* 1F30 */ { IOTA, PSILI },
    /* 1F31 */ { IOTA, DASIA },
    /* 1F32 */ { IOTA, PSILI_AND_VARIA },
    /* 1F33 */ { IOTA, DASIA_AND_VARIA },
    /* 1F34 */ { IOTA, PSILI_AND_OXIA },
    /* 1F35 */ { IOTA, DASIA_AND_OXIA },
    /* 1F36 */ { IOTA, PSILI_AND_PERISPOMENI },
    /* 1F37 */ { IOTA, DASIA_AND_PERISPOMENI },
    /* 1F38 */ { IOTA_CAP, PSILI },
    /* 1F39 */ { IOTA_CAP, DASIA },
    /* 1F3A */ { IOTA_CAP, PSILI_AND_VARIA },
    /* 1F3B */ { IOTA_CAP, DASIA_AND_VARIA },
    /* 1F3C */ { IOTA_CAP, PSILI_AND_OXIA },
    /* 1F3D */ { IOTA_CAP, DASIA_AND_OXIA },
    /* 1F3E */ { IOTA_CAP, PSILI_AND_PERISPOMENI },
    /* 1F3F */ { IOTA_CAP, DASIA_AND_PERISPOMENI },
    /* 1F40 */ { OMICRON, PSILI },
    /* 1F41 */ { OMICRON, DASIA },
    /* 1F42 */ { OMICRON, PSILI_AND_VARIA },
    /* 1F43 */ { OMICRON, DASIA_AND_VARIA },
    /* 1F44 */ { OMICRON, PSILI_AND_OXIA },
    /* 1F45 */ { OMICRON, DASIA_AND_OXIA },
    /* 1F46 */ { NOCHAR, NOCHAR },
    /* 1F47 */ { NOCHAR, NOCHAR },
    /* 1F48 */ { OMICRON_CAP, PSILI },
    /* 1F49 */ { OMICRON_CAP, DASIA },
    /* 1F4A */ { OMICRON_CAP, PSILI_AND_VARIA },
    /* 1F4B */ { OMICRON_CAP, DASIA_AND_VARIA },
    /* 1F4C */ { OMICRON_CAP, PSILI_AND_OXIA },
    /* 1F4D */ { OMICRON_CAP, DASIA_AND_OXIA },
    /* 1F4E */ { NOCHAR, NOCHAR },
    /* 1F4F */ { NOCHAR, NOCHAR },
    /* 1F50 */ { UPSILON, PSILI },
    /* 1F51 */ { UPSILON, DASIA },
    /* 1F52 */ { UPSILON, PSILI_AND_VARIA },
    /* 1F53 */ { UPSILON, DASIA_AND_VARIA },
    /* 1F54 */ { UPSILON, PSILI_AND_OXIA },
    /* 1F55 */ { UPSILON, DASIA_AND_OXIA },
    /* 1F56 */ { UPSILON, PSILI_AND_PERISPOMENI },
    /* 1F57 */ { UPSILON, DASIA_AND_PERISPOMENI },
    /* 1F58 */ { NOCHAR, NOCHAR },
    /* 1F59 */ { UPSILON_CAP, DASIA },
    /* 1F5A */ { NOCHAR, NOCHAR },
    /* 1F5B */ { UPSILON_CAP, DASIA_AND_VARIA },
    /* 1F5C */ { NOCHAR, NOCHAR },
    /* 1F5D */ { UPSILON_CAP, DASIA_AND_OXIA },
    /* 1F5E */ { NOCHAR, NOCHAR },
    /* 1F5F */ { UPSILON_CAP, DASIA_AND_PERISPOMENI },
    /* 1F60 */ { OMEGA, PSILI },
    /* 1F61 */ { OMEGA, DASIA },
    /* 1F62 */ { OMEGA, PSILI_AND_VARIA },
    /* 1F63 */ { OMEGA, DASIA_AND_VARIA },
    /* 1F64 */ { OMEGA, PSILI_AND_OXIA },
    /* 1F65 */ { OMEGA, DASIA_AND_OXIA },
    /* 1F66 */ { OMEGA, PSILI_AND_PERISPOMENI },
    /* 1F67 */ { OMEGA, DASIA_AND_PERISPOMENI },
    /* 1F68 */ { OMEGA_CAP, PSILI },
    /* 1F69 */ { OMEGA_CAP, DASIA },
    /* 1F6A */ { OMEGA_CAP, PSILI_AND_VARIA },
    /* 1F6B */ { OMEGA_CAP, DASIA_AND_VARIA },
    /* 1F6C */ { OMEGA_CAP, PSILI_AND_OXIA },
    /* 1F6D */ { OMEGA_CAP, DASIA_AND_OXIA },
    /* 1F6E */ { OMEGA_CAP, PSILI_AND_PERISPOMENI },
    /* 1F6F */ { OMEGA_CAP, DASIA_AND_PERISPOMENI },
    /* 1F70 */ { ALPHA, VARIA },
    /* 1F71 */ { ALPHA, OXIA },
    /* 1F72 */ { EPSILON, VARIA },
    /* 1F73 */ { EPSILON, OXIA },
    /* 1F74 */ { ETA, VARIA },
    /* 1F75 */ { ETA, OXIA },
    /* 1F76 */ { IOTA, VARIA },
    /* 1F77 */ { IOTA, OXIA },
    /* 1F78 */ { OMICRON, VARIA },
    /* 1F79 */ { OMICRON, OXIA },
    /* 1F7A */ { UPSILON, VARIA },
    /* 1F7B */ { UPSILON, OXIA },
    /* 1F7C */ { OMEGA, VARIA },
    /* 1F7D */ { OMEGA, OXIA },
    /* 1F7E */ { NOCHAR, NOCHAR },
    /* 1F7F */ { NOCHAR, NOCHAR },
    /* 1F80 */ { ALPHA, PSILI_AND_YPOGEGRAMMENI },
    /* 1F81 */ { ALPHA, DASIA_AND_YPOGEGRAMMENI },
    /* 1F82 */ { ALPHA, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F83 */ { ALPHA, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F84 */ { ALPHA, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F85 */ { ALPHA, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F86 */ { ALPHA, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F87 */ { ALPHA, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F88 */ { ALPHA_CAP, PSILI_AND_YPOGEGRAMMENI },
    /* 1F89 */ { ALPHA_CAP, DASIA_AND_YPOGEGRAMMENI },
    /* 1F8A */ { ALPHA_CAP, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F8B */ { ALPHA_CAP, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F8C */ { ALPHA_CAP, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F8D */ { ALPHA_CAP, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F8E */ { ALPHA_CAP, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F8F */ { ALPHA_CAP, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F90 */ { ETA, PSILI_AND_YPOGEGRAMMENI },
    /* 1F91 */ { ETA, DASIA_AND_YPOGEGRAMMENI },
    /* 1F92 */ { ETA, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F93 */ { ETA, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F94 */ { ETA, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F95 */ { ETA, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F96 */ { ETA, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F97 */ { ETA, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F98 */ { ETA_CAP, PSILI_AND_YPOGEGRAMMENI },
    /* 1F99 */ { ETA_CAP, DASIA_AND_YPOGEGRAMMENI },
    /* 1F9A */ { ETA_CAP, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F9B */ { ETA_CAP, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1F9C */ { ETA_CAP, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F9D */ { ETA_CAP, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1F9E */ { ETA_CAP, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1F9F */ { ETA_CAP, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FA0 */ { OMEGA, PSILI_AND_YPOGEGRAMMENI },
    /* 1FA1 */ { OMEGA, DASIA_AND_YPOGEGRAMMENI },
    /* 1FA2 */ { OMEGA, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1FA3 */ { OMEGA, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1FA4 */ { OMEGA, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1FA5 */ { OMEGA, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1FA6 */ { OMEGA, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FA7 */ { OMEGA, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FA8 */ { OMEGA_CAP, PSILI_AND_YPOGEGRAMMENI },
    /* 1FA9 */ { OMEGA_CAP, DASIA_AND_YPOGEGRAMMENI },
    /* 1FAA */ { OMEGA_CAP, PSILI_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1FAB */ { OMEGA_CAP, DASIA_AND_VARIA_AND_YPOGEGRAMMENI },
    /* 1FAC */ { OMEGA_CAP, PSILI_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1FAD */ { OMEGA_CAP, DASIA_AND_OXIA_AND_YPOGEGRAMMENI },
    /* 1FAE */ { OMEGA_CAP, PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FAF */ { OMEGA_CAP, DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FB0 */ { NOCHAR, NOCHAR },
    /* 1FB1 */ { ALPHA, MACRON_PRECOMPOSED },
    /* 1FB2 */ { ALPHA, VARIA_AND_YPOGEGRAMMENI },
    /* 1FB3 */ { ALPHA, YPOGEGRAMMENI },
    /* 1FB4 */ { ALPHA, OXIA_AND_YPOGEGRAMMENI },
    /* 1FB5 */ { NOCHAR, NOCHAR },
    /* 1FB6 */ { ALPHA, PERISPOMENI },
    /* 1FB7 */ { ALPHA, PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FB8 */ { NOCHAR, NOCHAR },
    /* 1FB9 */ { ALPHA_CAP, MACRON_PRECOMPOSED },
    /* 1FBA */ { ALPHA_CAP, VARIA },
    /* 1FBB */ { ALPHA_CAP, OXIA },
    /* 1FBC */ { ALPHA_CAP, YPOGEGRAMMENI },
    /* 1FBD */ { NOCHAR, NOCHAR },
    /* 1FBE */ { NOCHAR, NOCHAR },
    /* 1FBF */ { NOCHAR, NOCHAR },
    /* 1FC0 */ { NOCHAR, NOCHAR },
    /* 1FC1 */ { NOCHAR, NOCHAR },
    /* 1FC2 */ { ETA, VARIA_AND_YPOGEGRAMMENI },
    /* 1FC3 */ { ETA, YPOGEGRAMMENI },
    /* 1FC4 */ { ETA, OXIA_AND_YPOGEGRAMMENI },
    /* 1FC5 */ { NOCHAR, NOCHAR },
    /* 1FC6 */ { ETA, PERISPOMENI },
    /* 1FC7 */ { ETA, PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FC8 */ { EPSILON_CAP, VARIA },
    /* 1FC9 */ { EPSILON_CAP, OXIA },
    /* 1FCA */ { ETA_CAP, VARIA },
    /* 1FCB */ { ETA_CAP, OXIA },
    /* 1FCC */ { ETA_CAP, YPOGEGRAMMENI },
    /* 1FCD */ { NOCHAR, NOCHAR },
    /* 1FCE */ { NOCHAR, NOCHAR },
    /* 1FCF */ { NOCHAR, NOCHAR },
    /* 1FD0 */ { NOCHAR, NOCHAR },
    /* 1FD1 */ { IOTA, MACRON_PRECOMPOSED },
    /* 1FD2 */ { IOTA, DIALYTIKA_AND_VARIA },
    /* 1FD3 */ { IOTA, DIALYTIKA_AND_OXIA },
    /* 1FD4 */ { NOCHAR, NOCHAR },
    /* 1FD5 */ { NOCHAR, NOCHAR },
    /* 1FD6 */ { IOTA, PERISPOMENI },
    /* 1FD7 */ { IOTA, DIALYTIKA_AND_PERISPOMENON },
    /* 1FD8 */ { NOCHAR, NOCHAR },
    /* 1FD9 */ { IOTA_CAP, MACRON_PRECOMPOSED },
    /* 1FDA */ { IOTA_CAP, VARIA },
    /* 1FDB */ { IOTA_CAP, OXIA },
    /* 1FDC */ { NOCHAR, NOCHAR },
    /* 1FDD */ { NOCHAR, NOCHAR },
    /* 1FDE */ { NOCHAR, NOCHAR },
    /* 1FDF */ { NOCHAR, NOCHAR },
    /* 1FE0 */ { NOCHAR, NOCHAR },
    /* 1FE1 */ { UPSILON, MACRON_PRECOMPOSED },
    /* 1FE2 */ { UPSILON, DIALYTIKA_AND_VARIA },
    /* 1FE3 */ { UPSILON, DIALYTIKA_AND_OXIA },
    /* 1FE4 */ { NOCHAR, NOCHAR },
    /* 1FE5 */ { NOCHAR, NOCHAR },
    /* 1FE6 */ { UPSILON, PERISPOMENI },
    /* 1FE7 */ { UPSILON, DIALYTIKA_AND_PERISPOMENON },
    /* 1FE8 */ { NOCHAR, NOCHAR },
    /* 1FE9 */ { UPSILON_CAP, MACRON_PRECOMPOSED },
    /* 1FEA */ { UPSILON_CAP, VARIA },
    /* 1FEB */ { UPSILON_CAP, OXIA },
    /* 1FEC */ { NOCHAR, NOCHAR },
    /* 1FED */ { NOCHAR, NOCHAR },
    /* 1FEE */ { NOCHAR, NOCHAR },
    /* 1FEF */ { NOCHAR, NOCHAR },
    /* 1FF0 */ { NOCHAR, NOCHAR },
    /* 1FF1 */ { NOCHAR, NOCHAR },
    /* 1FF2 */ { OMEGA, VARIA_AND_YPOGEGRAMMENI },
    /* 1FF3 */ { OMEGA, YPOGEGRAMMENI },
    /* 1FF4 */ { OMEGA, OXIA_AND_YPOGEGRAMMENI },
    /* 1FF5 */ { NOCHAR, NOCHAR },
    /* 1FF6 */ { OMEGA, PERISPOMENI },
    /* 1FF7 */ { OMEGA, PERISPOMENI_AND_YPOGEGRAMMENI },
    /* 1FF8 */ { OMICRON_CAP, VARIA },
    /* 1FF9 */ { OMICRON_CAP, OXIA },
    /* 1FFA */ { OMEGA_CAP, VARIA },
    /* 1FFB */ { OMEGA_CAP, OXIA },
    /* 1FFC */ { OMEGA_CAP, YPOGEGRAMMENI },
    /* 1FFD */ { NOCHAR, NOCHAR },
    /* 1FFE */ { NOCHAR, NOCHAR },
    /* 1FFF */ { NOCHAR, NOCHAR }
};
    
short puaGreekLookUp[][2] = {
    /* EAF0 */ { ALPHA, MACRON_AND_GRAVE },
    /* EAF1 */ { NOCHAR, NOCHAR },
    /* EAF2 */ { NOCHAR, NOCHAR },
    /* EAF3 */ { ALPHA, MACRON_AND_SMOOTH_AND_GRAVE },
    /* EAF4 */ { ALPHA, MACRON_AND_ROUGH_AND_GRAVE },
    /* EAF5 */ { NOCHAR, NOCHAR },
    /* EAF6 */ { NOCHAR, NOCHAR },
    /* EAF7 */ { NOCHAR, NOCHAR },
    /* EAF8 */ { NOCHAR, NOCHAR },
    /* EAF9 */ { NOCHAR, NOCHAR },
    /* EAFA */ { NOCHAR, NOCHAR },
    /* EAFB */ { NOCHAR, NOCHAR },
    /* EAFC */ { NOCHAR, NOCHAR },
    /* EAFD */ { NOCHAR, NOCHAR },
    /* EAFE */ { NOCHAR, NOCHAR },
    /* EAFF */ { NOCHAR, NOCHAR },
    /* EB00 */ { ALPHA, MACRON_AND_ACUTE },
    /* EB01 */ { NOCHAR, NOCHAR },
    /* EB02 */ { NOCHAR, NOCHAR },
    /* EB03 */ { NOCHAR, NOCHAR },
    /* EB04 */ { ALPHA, MACRON_AND_SMOOTH },
    /* EB05 */ { ALPHA, MACRON_AND_ROUGH },
    /* EB06 */ { NOCHAR, NOCHAR },
    /* EB07 */ { ALPHA, MACRON_AND_SMOOTH_AND_ACUTE },
    /* EB08 */ { NOCHAR, NOCHAR },
    /* EB09 */ { ALPHA, MACRON_AND_ROUGH_AND_ACUTE },
    /* EB0A */ { NOCHAR, NOCHAR },
    /* EB0B */ { NOCHAR, NOCHAR },
    /* EB0C */ { NOCHAR, NOCHAR },
    /* EB0D */ { NOCHAR, NOCHAR },
    /* EB0E */ { NOCHAR, NOCHAR },
    /* EB0F */ { NOCHAR, NOCHAR },
    /* EB10 */ { NOCHAR, NOCHAR },
    /* EB11 */ { NOCHAR, NOCHAR },
    /* EB12 */ { NOCHAR, NOCHAR },
    /* EB13 */ { NOCHAR, NOCHAR },
    /* EB14 */ { NOCHAR, NOCHAR },
    /* EB15 */ { NOCHAR, NOCHAR },
    /* EB16 */ { NOCHAR, NOCHAR },
    /* EB17 */ { NOCHAR, NOCHAR },
    /* EB18 */ { NOCHAR, NOCHAR },
    /* EB19 */ { NOCHAR, NOCHAR },
    /* EB1A */ { NOCHAR, NOCHAR },
    /* EB1B */ { NOCHAR, NOCHAR },
    /* EB1C */ { NOCHAR, NOCHAR },
    /* EB1D */ { NOCHAR, NOCHAR },
    /* EB1E */ { NOCHAR, NOCHAR },
    /* EB1F */ { NOCHAR, NOCHAR },
    /* EB20 */ { NOCHAR, NOCHAR },
    /* EB21 */ { NOCHAR, NOCHAR },
    /* EB22 */ { NOCHAR, NOCHAR },
    /* EB23 */ { NOCHAR, NOCHAR },
    /* EB24 */ { NOCHAR, NOCHAR },
    /* EB25 */ { NOCHAR, NOCHAR },
    /* EB26 */ { NOCHAR, NOCHAR },
    /* EB27 */ { NOCHAR, NOCHAR },
    /* EB28 */ { NOCHAR, NOCHAR },
    /* EB29 */ { NOCHAR, NOCHAR },
    /* EB2A */ { NOCHAR, NOCHAR },
    /* EB2B */ { NOCHAR, NOCHAR },
    /* EB2C */ { NOCHAR, NOCHAR },
    /* EB2D */ { NOCHAR, NOCHAR },
    /* EB2E */ { NOCHAR, NOCHAR },
    /* EB2F */ { NOCHAR, NOCHAR },
    /* EB30 */ { NOCHAR, NOCHAR },
    /* EB31 */ { NOCHAR, NOCHAR },
    /* EB32 */ { NOCHAR, NOCHAR },
    /* EB33 */ { NOCHAR, NOCHAR },
    /* EB34 */ { NOCHAR, NOCHAR },
    /* EB35 */ { NOCHAR, NOCHAR },
    /* EB36 */ { NOCHAR, NOCHAR },
    /* EB37 */ { NOCHAR, NOCHAR },
    /* EB38 */ { IOTA, MACRON_AND_GRAVE },
    /* EB39 */ { IOTA, MACRON_AND_ACUTE },
    /* EB3A */ { NOCHAR, NOCHAR },
    /* EB3B */ { NOCHAR, NOCHAR },
    /* EB3C */ { IOTA, MACRON_AND_SMOOTH },
    /* EB3D */ { IOTA, MACRON_AND_SMOOTH_AND_ACUTE },
    /* EB3E */ { IOTA, MACRON_AND_ROUGH },
    /* EB3F */ { IOTA, MACRON_AND_ROUGH_AND_ACUTE },
    /* EB40 */ { NOCHAR, NOCHAR },
    /* EB41 */ { NOCHAR, NOCHAR },
    /* EB42 */ { NOCHAR, NOCHAR },
    /* EB43 */ { NOCHAR, NOCHAR },
    /* EB44 */ { NOCHAR, NOCHAR },
    /* EB45 */ { NOCHAR, NOCHAR },
    /* EB46 */ { NOCHAR, NOCHAR },
    /* EB47 */ { NOCHAR, NOCHAR },
    /* EB48 */ { NOCHAR, NOCHAR },
    /* EB49 */ { NOCHAR, NOCHAR },
    /* EB4A */ { NOCHAR, NOCHAR },
    /* EB4B */ { NOCHAR, NOCHAR },
    /* EB4C */ { NOCHAR, NOCHAR },
    /* EB4D */ { NOCHAR, NOCHAR },
    /* EB4E */ { NOCHAR, NOCHAR },
    /* EB4F */ { NOCHAR, NOCHAR },
    /* EB50 */ { NOCHAR, NOCHAR },
    /* EB51 */ { NOCHAR, NOCHAR },
    /* EB52 */ { NOCHAR, NOCHAR },
    /* EB53 */ { NOCHAR, NOCHAR },
    /* EB54 */ { IOTA, MACRON_AND_SMOOTH_AND_GRAVE },
    /* EB55 */ { IOTA, MACRON_AND_ROUGH_AND_GRAVE },
    /* EB56 */ { NOCHAR, NOCHAR },
    /* EB57 */ { NOCHAR, NOCHAR },
    /* EB58 */ { NOCHAR, NOCHAR },
    /* EB59 */ { NOCHAR, NOCHAR },
    /* EB5A */ { NOCHAR, NOCHAR },
    /* EB5B */ { NOCHAR, NOCHAR },
    /* EB5C */ { NOCHAR, NOCHAR },
    /* EB5D */ { NOCHAR, NOCHAR },
    /* EB5E */ { NOCHAR, NOCHAR },
    /* EB5F */ { NOCHAR, NOCHAR },
    /* EB60 */ { NOCHAR, NOCHAR },
    /* EB61 */ { NOCHAR, NOCHAR },
    /* EB62 */ { NOCHAR, NOCHAR },
    /* EB63 */ { NOCHAR, NOCHAR },
    /* EB64 */ { NOCHAR, NOCHAR },
    /* EB65 */ { NOCHAR, NOCHAR },
    /* EB66 */ { NOCHAR, NOCHAR },
    /* EB67 */ { NOCHAR, NOCHAR },
    /* EB68 */ { NOCHAR, NOCHAR },
    /* EB69 */ { NOCHAR, NOCHAR },
    /* EB6A */ { NOCHAR, NOCHAR },
    /* EB6B */ { NOCHAR, NOCHAR },
    /* EB6C */ { NOCHAR, NOCHAR },
    /* EB6D */ { NOCHAR, NOCHAR },
    /* EB6E */ { NOCHAR, NOCHAR },
    /* EB6F */ { UPSILON, MACRON_AND_GRAVE },
    /* EB70 */ { NOCHAR, NOCHAR },
    /* EB71 */ { UPSILON, MACRON_AND_SMOOTH_AND_GRAVE },
    /* EB72 */ { NOCHAR, NOCHAR },
    /* EB73 */ { NOCHAR, NOCHAR },
    /* EB74 */ { NOCHAR, NOCHAR },
    /* EB75 */ { UPSILON, MACRON_AND_ROUGH_AND_GRAVE },
    /* EB76 */ { NOCHAR, NOCHAR },
    /* EB77 */ { NOCHAR, NOCHAR },
    /* EB78 */ { NOCHAR, NOCHAR },
    /* EB79 */ { NOCHAR, NOCHAR },
    /* EB7A */ { UPSILON, MACRON_AND_ACUTE },
    /* EB7B */ { NOCHAR, NOCHAR },
    /* EB7C */ { NOCHAR, NOCHAR },
    /* EB7D */ { UPSILON, MACRON_AND_SMOOTH },
    /* EB7E */ { UPSILON, MACRON_AND_ROUGH },
    /* EB7F */ { UPSILON, MACRON_AND_SMOOTH_AND_ACUTE },
    /* EB80 */ { UPSILON, MACRON_AND_ROUGH_AND_ACUTE }
};

bool analyzePrecomposedLetterOLD(unsigned short letter, int *l, int *a)
{
    for (*l = 0; *l < NUM_VOWEL_CODES; (*l)++)
    {
        for (*a = 0; *a < NUM_ACCENT_CODES; (*a)++)
        {
            if (letter == letters[*l][*a])
            {
                //fprintf(stderr, "letter: %d, accent: %d", *l, *a);
                return true;
            }
        }
    }
    return false;
}

bool analyzePrecomposedLetter(unsigned short letter, int *l, int *a)
{
    int offset = 0;
    if (letter >= 0x0370 && letter <= 0x03FF)
    {
        offset = letter - 0x0370;
        if (basicGreekLookUp[offset][0] != NOCHAR)
        {
            *l = basicGreekLookUp[offset][0];
            *a = basicGreekLookUp[offset][1];
            //fprintf(stderr, "basic letter: %d, accent: %d", *l, *a);
            return true;
        }
    }
    else if (letter >= 0x1F00 && letter <= 0x1FFF)
    {
        offset = letter - 0x1F00;
        if (extendedGreekLookUp[offset][0] != NOCHAR) //this is broken, alpha and none both == 0
        {
            *l = extendedGreekLookUp[offset][0];
            *a = extendedGreekLookUp[offset][1];
            //fprintf(stderr, "extended letter: %d, accent: %d", *l, *a);
            return true;
        }
    }
    else if (letter >= 0xEAF0 && letter <= 0xEB80)
    {
        offset = letter - 0xEAF0;
        if (puaGreekLookUp[offset][0] != NOCHAR) //this is broken, alpha and none both == 0
        {
            *l = puaGreekLookUp[offset][0];
            *a = puaGreekLookUp[offset][1];
            //fprintf(stderr, "pua letter: %d, accent: %d", *l, *a);
            return true;
        }
    }
 
    return false;
}

int precomposedIndexToBitMask(int precomposedIndex, int diacriticMask)
{
    //don't initialize to false here because diacriticMask could have combining accents already set to true
    //make sure this is in order of enum so compiler can optimize switch
    switch (precomposedIndex)
    {
        case PSILI:
        diacriticMask |= _SMOOTH;
        break;
        case DASIA:
        diacriticMask |= _ROUGH;
        break;
        case OXIA: //both point to acute
        case TONOS:
        diacriticMask |= _ACUTE;
        break;
        case PSILI_AND_OXIA:
        diacriticMask |= (_SMOOTH | _ACUTE);
        break;
        case DASIA_AND_OXIA:
        diacriticMask |= (_ROUGH | _ACUTE);
        break;
        case VARIA:
        diacriticMask |= _GRAVE;
        break;
        case PSILI_AND_VARIA:
        diacriticMask |= (_SMOOTH | _GRAVE);
        break;
        case DASIA_AND_VARIA:
        diacriticMask |= (_ROUGH | _GRAVE);
        break;
        case PERISPOMENI:
        diacriticMask |= _CIRCUMFLEX;
        break;
        case PSILI_AND_PERISPOMENI:
        diacriticMask |= (_SMOOTH | _CIRCUMFLEX);
        break;
        case DASIA_AND_PERISPOMENI:
        diacriticMask |= (_ROUGH | _CIRCUMFLEX);
        break;
        case YPOGEGRAMMENI:
        diacriticMask |= _IOTA_SUB;
        break;
        case PSILI_AND_YPOGEGRAMMENI:
        diacriticMask |= (_SMOOTH | _IOTA_SUB);
        break;
        case DASIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_ROUGH | _IOTA_SUB);
        break;
        case OXIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_ACUTE | _IOTA_SUB);
        break;
        case PSILI_AND_OXIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_SMOOTH | _ACUTE | _IOTA_SUB);
        break;
        case DASIA_AND_OXIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_ROUGH | _ACUTE | _IOTA_SUB);
        break;
        case VARIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_GRAVE | _IOTA_SUB);
        break;
        case PSILI_AND_VARIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_SMOOTH | _GRAVE | _IOTA_SUB);
        break;
        case DASIA_AND_VARIA_AND_YPOGEGRAMMENI:
        diacriticMask |= (_ROUGH | _GRAVE | _IOTA_SUB);
        break;
        case PERISPOMENI_AND_YPOGEGRAMMENI:
        diacriticMask |= (_CIRCUMFLEX | _IOTA_SUB);
        break;
        case PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI:
        diacriticMask |= (_SMOOTH | _CIRCUMFLEX | _IOTA_SUB);
        break;
        case DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI:
        diacriticMask |= (_ROUGH | _CIRCUMFLEX | _IOTA_SUB);
        break;
        case DIALYTIKA:
        diacriticMask |= _DIAERESIS;
        break;
        case DIALYTIKA_AND_TONOS: //for both
        case DIALYTIKA_AND_OXIA:
        diacriticMask |= (_DIAERESIS | _ACUTE);
        break;
        case DIALYTIKA_AND_VARIA:
        diacriticMask |= (_DIAERESIS | _GRAVE);
        break;
        case DIALYTIKA_AND_PERISPOMENON:
        diacriticMask |= (_DIAERESIS | _CIRCUMFLEX);
        break;
        case MACRON_PRECOMPOSED:
        diacriticMask |= _MACRON;
        break;
#ifdef ALLOW_PRIVATE_USE_AREA
        case MACRON_AND_SMOOTH:
        diacriticMask |= (_MACRON | _SMOOTH);
        break;
        case MACRON_AND_SMOOTH_AND_ACUTE:
        diacriticMask |= (_MACRON | _SMOOTH | _ACUTE);
        break;
        case MACRON_AND_SMOOTH_AND_GRAVE:
        diacriticMask |= (_MACRON | _SMOOTH | _GRAVE);
        break;
        case MACRON_AND_ROUGH:
        diacriticMask |= (_MACRON | _ROUGH);
        break;
        case MACRON_AND_ROUGH_AND_ACUTE:
        diacriticMask |= (_MACRON | _ROUGH | _ACUTE);
        break;
        case MACRON_AND_ROUGH_AND_GRAVE:
        diacriticMask |= (_MACRON | _ROUGH | _GRAVE);
        break;
        case MACRON_AND_ACUTE:
        diacriticMask |= (_MACRON | _ACUTE);
        break;
        case MACRON_AND_GRAVE:
        diacriticMask |= (_MACRON | _GRAVE);
        break;
#endif
    }
    return diacriticMask;
}
/*
 //for testing
 //http://stackoverflow.com/questions/111928/is-there-a-printf-converter-to-print-in-binary-format
 const char *byte_to_binary(int x)
 {
 static char b[9];
 b[0] = '\0';
 
 int z;
 for (z = 128; z > 0; z >>= 1)
 {
 strcat(b, ((x & z) == z) ? "1" : "0");
 }
 
 return b;
 }
 */
//return 0 for invalid letter
unsigned short getPrecomposedLetter(int letterIndex, int diacriticMask)
{
    int accentIndex = 0;
    
    switch (diacriticMask)
    {
        case 0:
        accentIndex = NORMAL;
        break;
        case (_SMOOTH):
        accentIndex = PSILI;
        break;
        case (_ROUGH):
        accentIndex = DASIA;
        break;
        case (_ACUTE):
#ifdef USE_TONOS //this is defined, or not, in GreekUnicode.h
        accentIndex = TONOS;
#else
        accentIndex = OXIA;
#endif
        break;
        case (_SMOOTH | _ACUTE):
        accentIndex = PSILI_AND_OXIA;
        break;
        case (_ROUGH | _ACUTE):
        accentIndex = DASIA_AND_OXIA;
        break;
        case  (_GRAVE):
        accentIndex = VARIA;
        break;
        case (_SMOOTH | _GRAVE):
        accentIndex = PSILI_AND_VARIA;
        break;
        case (_ROUGH | _GRAVE):
        accentIndex = DASIA_AND_VARIA;
        break;
        case (_CIRCUMFLEX):
        accentIndex = PERISPOMENI;
        break;
        case (_SMOOTH | _CIRCUMFLEX):
        accentIndex = PSILI_AND_PERISPOMENI;
        break;
        case (_ROUGH | _CIRCUMFLEX):
        accentIndex = DASIA_AND_PERISPOMENI;
        break;
        case (_IOTA_SUB):
        accentIndex = YPOGEGRAMMENI;
        break;
        case (_SMOOTH | _IOTA_SUB):
        accentIndex = PSILI_AND_YPOGEGRAMMENI;
        break;
        case (_ROUGH | _IOTA_SUB):
        accentIndex = DASIA_AND_YPOGEGRAMMENI;
        break;
        case (_ACUTE | _IOTA_SUB):
        accentIndex = OXIA_AND_YPOGEGRAMMENI;
        break;
        case (_SMOOTH | _ACUTE | _IOTA_SUB):
        accentIndex = PSILI_AND_OXIA_AND_YPOGEGRAMMENI;
        break;
        case (_ROUGH | _ACUTE | _IOTA_SUB):
        accentIndex = DASIA_AND_OXIA_AND_YPOGEGRAMMENI;
        break;
        case (_GRAVE | _IOTA_SUB):
        accentIndex = VARIA_AND_YPOGEGRAMMENI;
        break;
        case (_SMOOTH | _GRAVE | _IOTA_SUB):
        accentIndex = PSILI_AND_VARIA_AND_YPOGEGRAMMENI;
        break;
        case (_ROUGH | _GRAVE | _IOTA_SUB):
        accentIndex = DASIA_AND_VARIA_AND_YPOGEGRAMMENI;
        break;
        case (_CIRCUMFLEX | _IOTA_SUB):
        accentIndex = PERISPOMENI_AND_YPOGEGRAMMENI;
        break;
        case (_SMOOTH | _CIRCUMFLEX | _IOTA_SUB):
        accentIndex = PSILI_AND_PERISPOMENI_AND_YPOGEGRAMMENI;
        break;
        case (_ROUGH | _CIRCUMFLEX | _IOTA_SUB):
        accentIndex = DASIA_AND_PERISPOMENI_AND_YPOGEGRAMMENI;
        break;
        case (_DIAERESIS):
        accentIndex = DIALYTIKA;
        break;
        case (_ACUTE | _DIAERESIS):
#ifdef USE_TONOS //this is defined, or not, in GreekUnicode.h
        accentIndex = DIALYTIKA_AND_TONOS;
#else
        accentIndex = DIALYTIKA_AND_OXIA;
#endif
        break;
        case (_GRAVE | _DIAERESIS):
        accentIndex = DIALYTIKA_AND_VARIA;
        break;
        case (_CIRCUMFLEX | _DIAERESIS):
        accentIndex = DIALYTIKA_AND_PERISPOMENON;
        break;
        case (_MACRON):
        accentIndex = MACRON_PRECOMPOSED;
        break;
#ifdef ALLOW_PRIVATE_USE_AREA
        case (_MACRON | _SMOOTH):
        accentIndex = MACRON_AND_SMOOTH;
        break;
        case (_MACRON | _SMOOTH | _ACUTE):
        accentIndex = MACRON_AND_SMOOTH_AND_ACUTE;
        break;
        case (_MACRON | _SMOOTH | _GRAVE):
        accentIndex = MACRON_AND_SMOOTH_AND_GRAVE;
        break;
        case (_MACRON | _ROUGH):
        accentIndex = MACRON_AND_ROUGH;
        break;
        case (_MACRON | _ROUGH | _ACUTE):
        accentIndex = MACRON_AND_ROUGH_AND_ACUTE;
        break;
        case (_MACRON | _ROUGH | _GRAVE):
        accentIndex = MACRON_AND_ROUGH_AND_GRAVE;
        break;
        case (_MACRON | _ACUTE):
        accentIndex = MACRON_AND_ACUTE;
        break;
        case (_MACRON | _GRAVE):
        accentIndex = MACRON_AND_GRAVE;
        break;
#endif
        default:
        return 0; //or set accent = 0 if none of these?
        break;
    }
    if (letterIndex > -1)
    return letters[letterIndex][accentIndex];
    else
    return 0;
}

bool isCombiningDiacritic(UCS2 l)
{
    switch (l)
    {
        case COMBINING_MACRON:
        case COMBINING_ACUTE:
        case COMBINING_GRAVE:
        case COMBINING_CIRCUMFLEX:
        case COMBINING_IOTA_SUBSCRIPT:
        case COMBINING_SMOOTH_BREATHING:
        case COMBINING_ROUGH_BREATHING:
        case COMBINING_DIAERESIS:
        case COMBINING_BREVE:
        return true;
    }
    
    return false;
}

bool isBareVowel(UCS2 l)
{
    switch (l)
    {
        case GREEK_SMALL_LETTER_ALPHA:
        case GREEK_SMALL_LETTER_EPSILON:
        case GREEK_SMALL_LETTER_ETA:
        case GREEK_SMALL_LETTER_IOTA:
        case GREEK_SMALL_LETTER_UPSILON:
        case GREEK_SMALL_LETTER_OMEGA:
        case GREEK_CAPITAL_LETTER_ALPHA:
        case GREEK_CAPITAL_LETTER_EPSILON:
        case GREEK_CAPITAL_LETTER_ETA:
        case GREEK_CAPITAL_LETTER_IOTA:
        case GREEK_CAPITAL_LETTER_UPSILON:
        case GREEK_CAPITAL_LETTER_OMEGA:
        return true;
    }
    
    return false;
}

int ucs2ToLetterCode(UCS2 l)
{
    if (l == GREEK_SMALL_LETTER_ALPHA)
    return ALPHA;
    else if (l == GREEK_SMALL_LETTER_EPSILON)
    return EPSILON;
    else if (l == GREEK_SMALL_LETTER_ETA)
    return ETA;
    else if (l == GREEK_SMALL_LETTER_IOTA)
    return IOTA;
    else if (l == GREEK_SMALL_LETTER_OMICRON)
    return OMICRON;
    else if (l == GREEK_SMALL_LETTER_UPSILON)
    return UPSILON;
    else if (l == GREEK_SMALL_LETTER_OMEGA)
    return OMEGA;
    else if (l == GREEK_CAPITAL_LETTER_ALPHA)
    return ALPHA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_EPSILON)
    return EPSILON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_ETA)
    return ETA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_IOTA)
    return IOTA_CAP;
    else if (l == GREEK_CAPITAL_LETTER_OMICRON)
    return OMICRON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_UPSILON)
    return UPSILON_CAP;
    else if (l == GREEK_CAPITAL_LETTER_OMEGA)
    return OMEGA_CAP;
    else
    return 0;
}

int letterCodeToUCS2(UCS2 l)
{
    if (l == ALPHA)
    return GREEK_SMALL_LETTER_ALPHA;
    else if (l == EPSILON)
    return GREEK_SMALL_LETTER_EPSILON;
    else if (l == ETA)
    return GREEK_SMALL_LETTER_ETA;
    else if (l == IOTA)
    return GREEK_SMALL_LETTER_IOTA;
    else if (l == OMICRON)
    return GREEK_SMALL_LETTER_OMICRON;
    else if (l == UPSILON)
    return GREEK_SMALL_LETTER_UPSILON;
    else if (l == OMEGA)
    return GREEK_SMALL_LETTER_OMEGA;
    else if (l == ALPHA_CAP)
    return GREEK_CAPITAL_LETTER_ALPHA;
    else if (l == EPSILON_CAP)
    return GREEK_CAPITAL_LETTER_EPSILON;
    else if (l == ETA_CAP)
    return GREEK_CAPITAL_LETTER_ETA;
    else if (l == IOTA_CAP)
    return GREEK_CAPITAL_LETTER_IOTA;
    else if (l == OMICRON_CAP)
    return GREEK_CAPITAL_LETTER_OMICRON;
    else if (l == UPSILON_CAP)
    return GREEK_CAPITAL_LETTER_UPSILON;
    else if (l == OMEGA_CAP)
    return GREEK_CAPITAL_LETTER_OMEGA;
    else
    return 0;
}

bool isLegalDiacriticForLetter(int letterCode, int accentToAdd)
{
    switch (accentToAdd)
    {
        case CIRCUMFLEX:
        if (letterCode != ALPHA && letterCode != ETA && letterCode != IOTA && letterCode != UPSILON && letterCode != OMEGA && letterCode != ALPHA_CAP && letterCode != ETA_CAP && letterCode != IOTA_CAP && letterCode != UPSILON_CAP && letterCode != OMEGA_CAP)
        {
            return false;
        }
        break;
        case MACRON:
        if (letterCode != ALPHA && letterCode != IOTA && letterCode != UPSILON && letterCode != ALPHA_CAP && letterCode != IOTA_CAP && letterCode != UPSILON_CAP)
        {
            return false;
        }
        break;
        case BREVE:
        if (letterCode != ALPHA && letterCode != IOTA && letterCode != UPSILON && letterCode != ALPHA_CAP && letterCode != IOTA_CAP && letterCode != UPSILON_CAP)
        {
            return false;
        }
        break;
        case IOTA_SUBSCRIPT:
        if (letterCode != ALPHA && letterCode != ETA && letterCode != OMEGA && letterCode != ALPHA_CAP && letterCode != ETA_CAP && letterCode != OMEGA_CAP)
        {
            return false;
        }
        break;
        case DIAERESIS:
        if (letterCode != IOTA && letterCode != UPSILON && letterCode != IOTA_CAP && letterCode != UPSILON_CAP)
        {
            return false;
        }
        break;
    }
    return true;
}

//adjusts diacritics based on one being added
int updateDiacritics(int letterCode, int accentToAdd, int accentBitMask, bool toggleOff)
{
    //keep in order of enum so compiler can optimize switch
    switch (accentToAdd)
    {
        case ACUTE:
        if (toggleOff && (accentBitMask & _ACUTE) == _ACUTE)
        accentBitMask &= ~_ACUTE;
        else
        accentBitMask |= _ACUTE;
        accentBitMask &= ~(_GRAVE | _CIRCUMFLEX); //turn off...
        break;
        case CIRCUMFLEX:
        if (toggleOff && (accentBitMask & _CIRCUMFLEX) == _CIRCUMFLEX)
        accentBitMask &= ~_CIRCUMFLEX;
        else
        accentBitMask |= _CIRCUMFLEX;
        accentBitMask &= ~(_ACUTE | _GRAVE | _MACRON); //turn off
        break;
        case GRAVE:
        if (toggleOff && (accentBitMask & _GRAVE) == _GRAVE)
        accentBitMask &= ~_GRAVE;
        else
        accentBitMask |= _GRAVE;
        accentBitMask &= ~(_ACUTE | _CIRCUMFLEX);
        break;
        case MACRON:
        if (toggleOff && (accentBitMask & _MACRON) == _MACRON)
        accentBitMask &= ~_MACRON;
        else
        accentBitMask |= _MACRON;
        accentBitMask &= ~_CIRCUMFLEX;
        accentBitMask &= ~_BREVE;
        break;
        case BREVE:
        if (toggleOff && (accentBitMask & _BREVE) == _BREVE)
        accentBitMask &= ~_BREVE;
        else
        accentBitMask |= _BREVE;
        accentBitMask &= ~_CIRCUMFLEX;
        accentBitMask &= ~_MACRON;
        break;
        case ROUGH_BREATHING:
        if (toggleOff && (accentBitMask & _ROUGH) == _ROUGH)
        accentBitMask &= ~_ROUGH;
        else
        accentBitMask |= _ROUGH;
        accentBitMask &= ~(_SMOOTH | _DIAERESIS);
        break;
        case SMOOTH_BREATHING:
        if (toggleOff && (accentBitMask & _SMOOTH) == _SMOOTH)
        accentBitMask &= ~_SMOOTH;
        else
        accentBitMask |= _SMOOTH;
        accentBitMask &= ~(_ROUGH | _DIAERESIS);
        break;
        case IOTA_SUBSCRIPT:
        if (toggleOff && (accentBitMask & _IOTA_SUB) == _IOTA_SUB)
        accentBitMask &= ~_IOTA_SUB;
        else
        accentBitMask |= _IOTA_SUB;
        break;
        case DIAERESIS:
        if (letterCode == IOTA_CAP || letterCode == UPSILON_CAP)
        {
            accentBitMask &= ~(_ACUTE | _GRAVE | _CIRCUMFLEX | _MACRON);
        }
        
        if (toggleOff && (accentBitMask & _DIAERESIS) == _DIAERESIS)
        accentBitMask &= ~_DIAERESIS;
        else
        accentBitMask |= _DIAERESIS;
        accentBitMask &= ~(_SMOOTH | _ROUGH);
        break;
    }
    return accentBitMask;
}

//passes back the letterCode and diacriticMask for this letter
//returns the number of characters or -1, if not valid or unknown
int analyzeLetter(UCS2 *ucs2String, int i, int len, int *letterCode, int *accentBitMask)
{
    unsigned char letterLen = 1;
    int precomposedIndex = 0;
    
    //this needs some fixing
    if (len > 1 )
    {
        for (int j = 1; j <= MAX_COMBINING && i + j < len; j++)
        {
            if (ucs2String[i + j] == COMBINING_ROUGH_BREATHING)
            {
                letterLen++;
                *accentBitMask |= _ROUGH;
            }
            else if (ucs2String[i + j] == COMBINING_SMOOTH_BREATHING)
            {
                letterLen++;
                *accentBitMask |= _SMOOTH;
            }
            else if (ucs2String[i + j] == COMBINING_ACUTE)
            {
                letterLen++;
                *accentBitMask |= _ACUTE;
            }
            else if (ucs2String[i + j] == COMBINING_GRAVE)
            {
                letterLen++;
                *accentBitMask |= _GRAVE;
            }
            else if (ucs2String[i + j] == COMBINING_CIRCUMFLEX)
            {
                letterLen++;
                *accentBitMask |= _CIRCUMFLEX;
            }
            else if (ucs2String[i + j] == COMBINING_MACRON)
            {
                letterLen++;
                *accentBitMask |= _MACRON;
            }
            else if (ucs2String[i + j] == COMBINING_BREVE)
            {
                letterLen++;
                *accentBitMask |= _BREVE;
            }
            else if (ucs2String[i + j] == COMBINING_IOTA_SUBSCRIPT)
            {
                letterLen++;
                *accentBitMask |= _IOTA_SUB;
            }
            else if (ucs2String[i + j] == COMBINING_DIAERESIS)
            {
                letterLen++;
                *accentBitMask |= _DIAERESIS;
            }
            else
            {
                break;
            }
        }
    }
    
    if (!analyzePrecomposedLetter(ucs2String[i], letterCode, &precomposedIndex))
    {
        return -1;
    }
    *accentBitMask = precomposedIndexToBitMask(precomposedIndex, *accentBitMask);
    
    return letterLen;
}

bool makeLetter(UCS2 *ucs2String, int *newLetterLen, int letterCode, int accentBitMask, int unicodeMode)
{
    //Use PUA, - almost all precomposing except alpha macron, breathing, accent, iota_sub, if iota_sub use combining
    //Use both, if macron use combining
    //Use only combining accents
    int i = 0;
    
    //fallback if macron + one more diacritic
    bool precomposingFallbackToComposing = false;
    if ((unicode_mode == PRECOMPOSED_MODE && (accentBitMask & _MACRON) == _MACRON) || (unicodeMode == PRECOMPOSED_WITH_PUA_MODE && (accentBitMask & (_MACRON | _DIAERESIS)) == (_MACRON | _DIAERESIS)))
    {
        if ((accentBitMask & ~_MACRON) != 0)//if any other bits set besides macron
        {
            precomposingFallbackToComposing = true;
        }
    }
    else if ((accentBitMask & _BREVE) == _BREVE)
    {
        precomposingFallbackToComposing = true;
    }
    else if (unicodeMode == PRECOMPOSED_HC_MODE && (accentBitMask & _MACRON) == _MACRON)
    {
        //this is legacy for the hoplite challenge app which uses combining macron even if no other diacritics
        precomposingFallbackToComposing = true;
    }
    
    *newLetterLen = 1;
    if (unicode_mode == COMBINING_ONLY_MODE || precomposingFallbackToComposing)
    {
        if ((accentBitMask & _MACRON) == _MACRON)
        (*newLetterLen)++;
        if ((accentBitMask & _BREVE) == _BREVE)
        (*newLetterLen)++;
        if ((accentBitMask & _SMOOTH) == _SMOOTH)
        (*newLetterLen)++;
        if ((accentBitMask & _ROUGH) == _ROUGH)
        (*newLetterLen)++;
        if ((accentBitMask & _ACUTE) == _ACUTE)
        (*newLetterLen)++;
        if ((accentBitMask & _GRAVE) == _GRAVE)
        (*newLetterLen)++;
        if ((accentBitMask & _CIRCUMFLEX) == _CIRCUMFLEX)
        (*newLetterLen)++;
        if ((accentBitMask & _IOTA_SUB) == _IOTA_SUB)
        (*newLetterLen)++;
        if ((accentBitMask & _DIAERESIS) == _DIAERESIS)
        (*newLetterLen)++;
        
        ucs2String[i] = letterCodeToUCS2(letterCode); //set base letter
        
        unsigned char numAccents = 1;
        //loop so that order is determined by combiningAccents array
        for (int k = 0; k < NUM_COMBINING_ACCENTS; k++)
        {
            if (combiningAccents[k] == COMBINING_MACRON && (accentBitMask & _MACRON) == _MACRON)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_BREVE && (accentBitMask & _BREVE) == _BREVE)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_ROUGH_BREATHING && (accentBitMask & _ROUGH) == _ROUGH)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_SMOOTH_BREATHING && (accentBitMask & _SMOOTH) == _SMOOTH)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_ACUTE && (accentBitMask & _ACUTE) == _ACUTE)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_GRAVE && (accentBitMask & _GRAVE) == _GRAVE)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_CIRCUMFLEX && (accentBitMask & _CIRCUMFLEX) == _CIRCUMFLEX)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_IOTA_SUBSCRIPT && (accentBitMask & _IOTA_SUB) == _IOTA_SUB)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
            else if (combiningAccents[k] == COMBINING_DIAERESIS && (accentBitMask & _DIAERESIS) == _DIAERESIS)
            {
                ucs2String[i + numAccents] = combiningAccents[k];
                numAccents++;
            }
        }
        return true;
    }
    else
    {
        if (unicode_mode == PRECOMPOSED_WITH_PUA_MODE && (accentBitMask & (_IOTA_SUB | _MACRON)) == (_IOTA_SUB | _MACRON))
        {
            (*newLetterLen)++;
        }
        
        if (unicode_mode == PRECOMPOSED_WITH_PUA_MODE && (accentBitMask & (_IOTA_SUB | _MACRON)) == (_IOTA_SUB | _MACRON))
        {
            ucs2String[i+1] = COMBINING_IOTA_SUBSCRIPT;
            accentBitMask &= ~_IOTA_SUB; //so we don't get two iota subscripts
        }
        
        unsigned short ucs2 = getPrecomposedLetter(letterCode, accentBitMask);
        if (ucs2 != 0)
        {
            ucs2String[i] = ucs2;
            return true;
        }
        else
        {
            return false;
        }
        
        //fprintf(stderr, "final len: %d\n", *len);
    }
}

UCS2 getSpacingDiacritic(int diacritic)
{
    switch (diacritic)
    {
        case ACUTE:
        return 0x00B4;
        break;
        case GRAVE:
        return 0x0060;
        break;
        case CIRCUMFLEX:
        return 0x005E;
        break;
        case MACRON:
        return 0x00AF;
        break;
        case BREVE:
        return 0x02D8;
        break;
        case DIAERESIS:
        return 0x00A8;
        break;
        case ROUGH_BREATHING:
        return 0x02BD;
        break;
        case SMOOTH_BREATHING:
        return 0x02BC;
        break;
        case IOTA_SUBSCRIPT:
        return 0x037A;
        break;
        default:
        return 0;
    }
}

//there should be room for a least MAX_COMBINING more characters at the end of ucs2String, in case it needs to grow
void accentSyllable(UCS2 *ucs2String, int i, int *len, int accentToAdd, bool toggleOff, int unicodeMode)
{
    if (unicodeMode != PRECOMPOSED_MODE && unicodeMode != PRECOMPOSED_WITH_PUA_MODE && unicodeMode != COMBINING_ONLY_MODE && unicodeMode != PRECOMPOSED_HC_MODE)
    {
        unicodeMode = PRECOMPOSED_MODE;
    }
    unicode_mode = unicodeMode;
    
    if (*len < 1) {
        if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                ucs2String[i] = sd;
                *len = 1;
            }
        }
        return;
    }
    
    //1. handle consonants
    if (ucs2String[i] == GREEK_SMALL_LETTER_RHO && accentToAdd == ROUGH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO_WITH_DASIA;
        return;
    }
    else if (ucs2String[i] == GREEK_SMALL_LETTER_RHO_WITH_DASIA && accentToAdd == ROUGH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO;
        return;
    }
    else if (ucs2String[i] == GREEK_CAPITAL_LETTER_RHO && accentToAdd == ROUGH_BREATHING)
    {
        ucs2String[i] = GREEK_CAPITAL_LETTER_RHO_WITH_DASIA;
        return;
    }
    else if (ucs2String[i] == GREEK_CAPITAL_LETTER_RHO_WITH_DASIA && accentToAdd == ROUGH_BREATHING)
    {
        ucs2String[i] = GREEK_CAPITAL_LETTER_RHO;
        return;
    }
    else if (ucs2String[i] == GREEK_SMALL_LETTER_RHO_WITH_PSILI && accentToAdd == ROUGH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO_WITH_DASIA;
        return;
    }
#ifdef ALLOW_RHO_WITH_PSILI
    else if (ucs2String[i] == GREEK_SMALL_LETTER_RHO && accentToAdd == SMOOTH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO_WITH_PSILI;
        return;
    }
    else if (ucs2String[i] == GREEK_SMALL_LETTER_RHO_WITH_PSILI && accentToAdd == SMOOTH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO;
        return;
    }
    else if (ucs2String[i] == GREEK_SMALL_LETTER_RHO_WITH_DASIA && accentToAdd == SMOOTH_BREATHING)
    {
        ucs2String[i] = GREEK_SMALL_LETTER_RHO_WITH_PSILI;
        return;
    }
#endif
    else if (ucs2String[i] == GREEK_SMALL_LETTER_NU && accentToAdd == SURROUNDING_PARENTHESES)
    {
        /*rightShiftFromOffsetSteps(ucs2String, i, 2, len);
         ucs2String[i] = LEFT_PARENTHESIS;
         ucs2String[i+1] = GREEK_SMALL_LETTER_NU;
         ucs2String[i+2] = RIGHT_PARENTHESIS; */
        splice(ucs2String, len, 1024, i, 1, (UCS2[]){LEFT_PARENTHESIS,GREEK_SMALL_LETTER_NU,RIGHT_PARENTHESIS }, 3);
        return;
    }
    
    //2. now analyze what is currently there
    int letterCode = 0;
    int accentBitMask = 0;
    
    //this will be -1 on error
    int letterLen = analyzeLetter(ucs2String, i, *len, &letterCode, &accentBitMask);
    if (letterLen < 1) {
        if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                ucs2String[i + 1] = sd;
                *len += 1;
            }
        }
        return;
    }
    //2.5: return if this diacritic isn't legal for the letter it's being added to
    if (!isLegalDiacriticForLetter(letterCode, accentToAdd)) {
        if (addSpacingDiacriticIfNotLegal) {
            UCS2 sd = getSpacingDiacritic(accentToAdd);
            if (sd) {
                ucs2String[i + 1] = sd;
                *len += 1;
            }
        }
        return;
    }
    
    //3. this changes old letter analysis to the one we want
    accentBitMask = updateDiacritics(letterCode, accentToAdd, accentBitMask, toggleOff);
    
    //4. this creates the new letter, either with combining or precomposed accents
    UCS2 buffer[MAX_COMBINING]; //this is letter plus max combining
    int newLetterLen = 0;
    if (!makeLetter(buffer, &newLetterLen, letterCode, accentBitMask, unicodeMode))
    return;
    
    //5. make room for letter or decrease it if it is shrinking
    splice(ucs2String, len, 1024, i, letterLen, buffer, newLetterLen);
}

/*
 void accentSyllableUtf8(char *utf8, int accent, bool toggleOff)
 {
 
 UCS2 ucs2[20];
 unsigned long len = strlen(utf8);
 utf8_to_ucs2_string((unsigned char*)&utf8[len - 5], ucs2, (int*)&len);
 
 accentSyllable(ucs2, (int)len, (int*)&len, accent, toggleOff);
 
 ucs2_to_utf8_string(ucs2, (int)len, (unsigned char*)utf8);
 }
 */

//helper function to make it easier to import into swift
/*
 void accentSyllable16(uint16_t *ucs2String, int i, int *len, int accent, bool toggleOff, int mode)
 {
 accentSyllable2((UCS2*)ucs2String, i, len, accent, toggleOff, mode);
 }
 */
